version: '2'
services:
    izzibus-app:
        image: izzibus
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://izzibus-postgresql:5432/izzibus
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    izzibus-postgresql:
        extends:
            file: postgresql.yml
            service: izzibus-postgresql
